name: Build APK

on:
  push:
    branches: [ main ] # Só gera o APK quando a main é atualizada

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Baixa seu código

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17' # Versão padrão para Flutter em 2026

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependências
        run: flutter pub get

      - name: Rodar Testes
        run: flutter test # O APK só será gerado se os testes passarem!

      - name: Build APK Release
        run: flutter build apk --release

      - name: Salvar APK como Artefato
        uses: actions/upload-artifact@v4
        with:
          name: Alembro # Nome do arquivo para download
          path: build/app/outputs/flutter-apk/Alembro.apk
